rm -r out

python -m src.main HAM10000 sampling ham10000 gan \
--n-samples 10000 \
--alpha 0.99 \
--batch-norm \
--d-iters 1 \
--g-iters 1 \
--data-bs 1000 \
--disc-h-layers 2 \
--disc-h-size -1 \
--disc-lr 1e-8 \
--disc-type "biggan" \
--eval-samples 100 \
--feature-maps 64 \
--gan-arch "biggan" \
--gan-mode "wgan" \
--gp-weight 10 \
--grad-acc 1 \
--grad-clamp 0.1 \
--h-layers 4 \
--h-size 2 \
--lr 2e-8 \
--gpu 0 \
--max-epochs 1000 \
--max-lambda 0.01 \
--min-lambda 0.0001 \
--ncm-bs 256 \
--no-repr \
--patience 250 \
--rep-type "real" \
--custom-query \
--scale-h-size \
--scale-u-size \
--u-size 2 \
--wandb \
--wandb-org-name "paulkroe" \
--wandb-project-name  "NeuralCausalAbstractions"